### ISSUE TITLE
De controller loop en 'AI'

### ISSUE THREAD

**Issue by NanneHuiges** [Ordina-JTech/hack-a-drone#1]
Het is me nog niet duidelijk geworden hoe de controller-loop en het commandos sturen zou moeten werken. Wat ik denk te zien is dat de controller een loop doet die het 'huidige' commando steeds stuurt (met een sleep van 50ms er tussen).

Mijn aanname was dat dit vooral handig zou zijn voor de keyboard-functie: immers, je 'wacht' dan gewoon op veranderende commandos, en dan kun je die sturen.
Opstijgen gaat als ik het goed heb door `takeOff` te sturen, maar die kan ook weer op false (als je de leftarrow loslaat).
Doorredenerend dacht ik de loop uit te kunnen zetten in AI mode, en dan gewoon een command sturen, slapen, en een ander command sturen.

Echter, dit lijkt niet te werken. **Er is dus kennelijk herhaling van het command-signaal nodig om de drone te overtuigen van opstijgen?** Maar omdat in keyboard-mode het loslaten ook weer een takeoff = false stuurt, is het volgens mij niet zo dat je oneindig dat takeoff signaal moet sturen b.v.

Waar ik heen wil is achterhalen of het inderdaad nodig is om commandos herhaaldelijk te sturen. Als dat zo is, dan heeft het niet veel zin om te proberen die loop er uit te halen, of iig niet op de manier die ik aan het proberen was :)

Weet 1 van jullie misschien wat bv de controller / de app doet? Commands moeten iedere n ms gestuurd worden, anders gebeurd er niets oid?

**Comment by NanneHuiges** [comment]
Het herhaaldelijk sturen van een signaal lijkt het best te werken. Waarom je opstijgen en landen apart kan doen, bijde met een true EN een false, is me nog niet duidelijk.

Maar dit lijkt iig iets te doen ;)

https://github.com/NanneHuiges/hack-a-drone/tree/nh/ai_noloop

**Comment by nberlijn** [comment]
@NanneHuiges bedankt voor het uitbreiden van de AI! Jouw code heb ik succesvol verwerkt in de applicatie.
