### ISSUE TITLE
GUI werkt alleen met IntelliJ

### ISSUE THREAD

**Issue by nberlijn** [Ordina-JTech/hack-a-drone#2]
Momenteel werkt de GUI alleen met IntelliJ. Hoewel, in Eclipse is het wel mogelijk de GUI aan de hand van de JFormDesigner-plugin werkend te krijgen. Op dit moment wordt er aan deze issue gewerkt.

**Comment by nberlijn** [comment]
De IntelliJ FormBuilder is verwijderd en herbouwd met Swing.

**Comment by pnmtjonahen** [comment]
Kijk op mij gitgub account daar staat een versie die zonder intellij werkt


Op ma 19 jun. 2017 11:43 schreef Nils Berlijn <notifications@github.com>:
